#!/usr/bin/env bash
# To install Nginx on server
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"

sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx restart
